set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]



set_property PACKAGE_PIN K17 [get_ports {sel_in[6]}]
set_property PACKAGE_PIN M18 [get_ports {sel_in[5]}]
set_property PACKAGE_PIN N17 [get_ports {sel_in[4]}]
set_property PACKAGE_PIN P18 [get_ports {sel_in[3]}]
set_property PACKAGE_PIN L17 [get_ports {sel_in[2]}]
set_property PACKAGE_PIN M19 [get_ports {sel_in[1]}]
set_property PACKAGE_PIN P17 [get_ports {sel_in[0]}]
set_property PACKAGE_PIN J3 [get_ports {p1[1]}]
set_property PACKAGE_PIN L3 [get_ports {p1[0]}]
set_property PACKAGE_PIN M2 [get_ports {p2[1]}]
set_property PACKAGE_PIN N2 [get_ports {p2[0]}]
set_property PACKAGE_PIN K3 [get_ports {p3[1]}]
set_property PACKAGE_PIN M3 [get_ports {p3[0]}]

set_property PACKAGE_PIN A14 [get_ports {seg1[0]}]
set_property PACKAGE_PIN A16 [get_ports {seg1[1]}]
set_property PACKAGE_PIN B15 [get_ports {seg1[2]}]
set_property PACKAGE_PIN B16 [get_ports {seg1[3]}]
set_property PACKAGE_PIN A15 [get_ports {seg1[4]}]
set_property PACKAGE_PIN A17 [get_ports {seg1[5]}]
set_property PACKAGE_PIN C15 [get_ports {seg1[6]}] 
set_property PACKAGE_PIN C16 [get_ports {seg1[7]}] 

set_property PACKAGE_PIN M1 [get_ports {seg2[0]}]
set_property PACKAGE_PIN N1 [get_ports {seg2[1]}]
set_property PACKAGE_PIN J2 [get_ports {seg2[2]}]
set_property PACKAGE_PIN G2 [get_ports {seg2[3]}]
set_property PACKAGE_PIN H1 [get_ports {seg2[4]}]
set_property PACKAGE_PIN K2 [get_ports {seg2[5]}]
set_property PACKAGE_PIN H2 [get_ports {seg2[6]}]
set_property PACKAGE_PIN G3 [get_ports {seg2[7]}] 

set_property PACKAGE_PIN J1 [get_ports {clk}]
set_property PACKAGE_PIN L2 [get_ports {same}]



set_property IOSTANDARD LVCMOS18 [get_ports {sel_in[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sel_in[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sel_in[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sel_in[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sel_in[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sel_in[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sel_in[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports {p1[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {p1[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {p2[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {p2[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {p3[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {p3[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports {seg1[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg1[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg1[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg1[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg1[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg1[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg1[6]}] 
set_property IOSTANDARD LVCMOS18 [get_ports {seg1[7]}] 

set_property IOSTANDARD LVCMOS18 [get_ports {seg2[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg2[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg2[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg2[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg2[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg2[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg2[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg2[7]}] 

set_property IOSTANDARD LVCMOS18 [get_ports {clk}]
set_property IOSTANDARD LVCMOS18 [get_ports {same}]